---
- name: Install Docker 
  hosts: localhost
  become: true
  tasks:
    - name: Was NodeJS installed?
      stat:
        path: /usr/bin/node
      ignore_errors: true
      register: node

    - name: Was npm installed
      stat:
        path: /ust/bin/npm
      ignore_errors: true
      register: npm
    
    - name: Install NodeJS
      import_tasks: installnodejs.yml
 
    - name: Git clone
      git:
        repo: https://gitfront.io/r/user-6058779/jrgijZuoZWKG/nodejs-todo.git
        dest: /home/ub/todo
      ignore_errors: true

    - name: Start server with NodeJS helps
      command: 'node /home/ub/todo/index.js &'

        
